import { useState, useEffect, useRef, useCallback, useMemo } from 'preact/hooks';
import { useTts } from '@soniox/react';
import { Button, Panel, Select } from './components';

const STATE_COLORS = {
  idle: 'bg-gray-200 text-gray-600',
  connecting: 'bg-yellow-100 text-yellow-700',
  speaking: 'bg-green-100 text-green-700',
  stopping: 'bg-gray-200 text-gray-600',
  error: 'bg-red-100 text-red-700',
};

const DEFAULT_TEXT = 'Hello from the Soniox SDK demo. This sentence is generated by text-to-speech.';
const DEFAULT_VOICE = 'Adrian';

export function TtsTab() {
  const [mode, setMode] = useState('websocket');
  const [text, setText] = useState(DEFAULT_TEXT);
  const [language, setLanguage] = useState('en');
  const [models, setModels] = useState([]);
  const [modelId, setModelId] = useState('');
  const [voiceId, setVoiceId] = useState(DEFAULT_VOICE);
  const [modelsError, setModelsError] = useState('');
  const [audioUrl, setAudioUrl] = useState(null);

  const chunksRef = useRef([]);
  const audioUrlRef = useRef(null);
  const audioRef = useRef(null);

  const replaceAudioUrl = useCallback((next) => {
    if (audioUrlRef.current) URL.revokeObjectURL(audioUrlRef.current);
    audioUrlRef.current = next;
    setAudioUrl(next);
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch('/tts/models');
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        if (cancelled) return;
        const list = Array.isArray(data.models) ? data.models : [];
        setModels(list);
        if (list.length > 0) {
          const first = list[0];
          setModelId(first.id);
          if (first.voices?.length) setVoiceId(first.voices[0].id);
        }
      } catch (err) {
        if (!cancelled) setModelsError(err.message);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    return () => {
      if (audioUrlRef.current) {
        URL.revokeObjectURL(audioUrlRef.current);
        audioUrlRef.current = null;
      }
    };
  }, []);

  useEffect(() => {
    if (audioUrl && audioRef.current) {
      void audioRef.current.play().catch(() => {});
    }
  }, [audioUrl]);

  const currentModel = useMemo(() => models.find((m) => m.id === modelId), [models, modelId]);
  const voices = currentModel?.voices ?? [];

  const onAudio = useCallback((chunk) => {
    chunksRef.current.push(chunk);
  }, []);

  const onTerminated = useCallback(() => {
    const chunks = chunksRef.current;
    if (chunks.length === 0) return;
    let totalBytes = 0;
    for (const c of chunks) totalBytes += c.byteLength;
    const combined = new Uint8Array(totalBytes);
    let offset = 0;
    for (const c of chunks) {
      combined.set(c, offset);
      offset += c.byteLength;
    }
    const blob = new Blob([combined], { type: 'audio/wav' });
    replaceAudioUrl(URL.createObjectURL(blob));
  }, [replaceAudioUrl]);

  const ttsOptions = useMemo(
    () => ({
      mode,
      model: modelId || undefined,
      voice: voiceId || DEFAULT_VOICE,
      language: language.trim() || 'en',
      audio_format: 'wav',
      onAudio,
      onTerminated,
    }),
    [mode, modelId, voiceId, language, onAudio, onTerminated]
  );

  const { state, isConnecting, isSpeaking, error, speak, cancel } = useTts(ttsOptions);

  const busy = isConnecting || isSpeaking;

  const resetAudio = useCallback(() => {
    chunksRef.current = [];
    replaceAudioUrl(null);
  }, [replaceAudioUrl]);

  const onModeChange = useCallback(
    (next) => {
      if (next === mode) return;
      if (busy) cancel();
      resetAudio();
      setMode(next);
    },
    [mode, busy, cancel, resetAudio]
  );

  const onSpeak = useCallback(() => {
    if (!text.trim()) return;
    resetAudio();
    speak(text);
  }, [text, speak, resetAudio]);

  const modelOptions = models.length
    ? models.map((m) => ({ value: m.id, label: m.name || m.id }))
    : [{ value: '', label: 'Loading models…' }];
  const voiceOptions = voices.length
    ? voices.map((v) => ({ value: v.id, label: v.id }))
    : [{ value: DEFAULT_VOICE, label: DEFAULT_VOICE }];

  return (
    <div className="mt-2">
      <p className="text-sm text-gray-500 mt-4">
        Text-to-Speech using <code className="bg-gray-100 px-1 rounded">@soniox/react</code>'s{' '}
        <code className="bg-gray-100 px-1 rounded">useTts</code> hook. Both modes run entirely in the browser — the
        SonioxProvider mints a <code className="bg-gray-100 px-1 rounded">tts_rt</code>-scoped temporary API key via{' '}
        <code className="bg-gray-100 px-1 rounded">ConfigContext.usage</code>.
      </p>

      <div className="flex items-center gap-2 mt-6">
        <span className="text-sm font-semibold text-gray-700">Mode:</span>
        <div className="inline-flex rounded-md overflow-hidden border border-gray-300">
          <button
            className={`px-4 py-1.5 text-sm font-semibold transition-colors ${mode === 'websocket' ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-50'}`}
            onClick={() => onModeChange('websocket')}
          >
            Realtime (WebSocket)
          </button>
          <button
            className={`px-4 py-1.5 text-sm font-semibold transition-colors border-l border-gray-300 ${mode === 'rest' ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 hover:bg-gray-50'}`}
            onClick={() => onModeChange('rest')}
          >
            REST
          </button>
        </div>
      </div>

      <Panel title="Text">
        <textarea
          rows={3}
          value={text}
          onInput={(e) => setText(e.target.value)}
          className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </Panel>

      <Panel title="Voice & language">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 items-end">
          <Select
            label="Model"
            value={modelId}
            onChange={(id) => {
              setModelId(id);
              const m = models.find((m) => m.id === id);
              if (m?.voices?.length) setVoiceId(m.voices[0].id);
            }}
            options={modelOptions}
          />
          <Select label="Voice" value={voiceId} onChange={setVoiceId} options={voiceOptions} />
          <label className="flex flex-col gap-1 font-semibold">
            Language
            <input
              type="text"
              className="px-3 py-2 text-base font-normal border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={language}
              onInput={(e) => setLanguage(e.target.value)}
              placeholder="en"
            />
          </label>
        </div>
        {modelsError && (
          <div className="mt-2 text-xs text-red-600">
            Failed to load TTS models: {modelsError}. Falling back to <code>{DEFAULT_VOICE}</code>.
          </div>
        )}
        <div className="mt-2 text-xs text-gray-500">
          Audio format is fixed to <code>wav</code> in this demo.
        </div>
      </Panel>

      <div className="flex flex-wrap items-center gap-3 mt-4">
        <Button onClick={onSpeak} disabled={busy || !text.trim()}>
          {busy ? 'Generating…' : 'Speak'}
        </Button>
        {busy && (
          <Button onClick={cancel} variant="secondary">
            Cancel
          </Button>
        )}
        <span
          className={`rounded-full px-3 py-0.5 text-xs font-medium ${STATE_COLORS[state] ?? 'bg-gray-200 text-gray-600'}`}
        >
          {state}
        </span>
      </div>

      {error && <div className="mt-3 text-sm text-red-600">Error: {error.message}</div>}

      {audioUrl && (
        <div className="mt-4">
          <audio ref={audioRef} src={audioUrl} controls className="w-full" />
        </div>
      )}
    </div>
  );
}
