'use client';

import { useTts } from '@soniox/react';
import { useCallback, useEffect, useRef, useState } from 'react';

import { Button } from '@/components/button';

const STATE_COLORS: Record<string, string> = {
  idle: 'bg-gray-200 text-gray-600',
  connecting: 'bg-yellow-100 text-yellow-700',
  speaking: 'bg-green-100 text-green-700',
  stopping: 'bg-gray-200 text-gray-600',
  error: 'bg-red-100 text-red-600',
};

export default function TextToSpeech() {
  const [text, setText] = useState(
    'Hello from the Soniox Next.js example. This sentence is generated by text-to-speech.'
  );
  const [voice, setVoice] = useState('Adrian');
  const [language, setLanguage] = useState('en');
  const [audioUrl, setAudioUrl] = useState<string | null>(null);

  const audioRef = useRef<HTMLAudioElement | null>(null);
  const chunksRef = useRef<Uint8Array[]>([]);
  const audioUrlRef = useRef<string | null>(null);

  const replaceAudioUrl = useCallback((next: string | null) => {
    if (audioUrlRef.current) URL.revokeObjectURL(audioUrlRef.current);
    audioUrlRef.current = next;
    setAudioUrl(next);
  }, []);

  const { state, isConnecting, isSpeaking, error, speak, cancel } = useTts({
    voice,
    model: 'tts-rt-v1',
    language,
    audio_format: 'wav',
    onAudio: (chunk) => {
      chunksRef.current.push(chunk);
    },
    onTerminated: () => {
      const chunks = chunksRef.current;
      let totalBytes = 0;
      for (const c of chunks) totalBytes += c.byteLength;
      const combined = new Uint8Array(totalBytes);
      let offset = 0;
      for (const c of chunks) {
        combined.set(c, offset);
        offset += c.byteLength;
      }
      const blob = new Blob([combined], { type: 'audio/wav' });
      replaceAudioUrl(URL.createObjectURL(blob));
    },
  });

  useEffect(() => {
    return () => {
      if (audioUrlRef.current) {
        URL.revokeObjectURL(audioUrlRef.current);
        audioUrlRef.current = null;
      }
    };
  }, []);

  useEffect(() => {
    if (audioUrl && audioRef.current) {
      void audioRef.current.play().catch(() => {});
    }
  }, [audioUrl]);

  const onSpeak = useCallback(() => {
    if (!text.trim()) return;
    chunksRef.current = [];
    replaceAudioUrl(null);
    speak(text);
  }, [text, speak, replaceAudioUrl]);

  const busy = isConnecting || isSpeaking;

  return (
    <div className="flex flex-col gap-4 w-full">
      <label className="text-sm font-medium text-gray-700" htmlFor="ttsText">
        Text
      </label>
      <textarea
        id="ttsText"
        rows={3}
        value={text}
        onChange={(e) => setText(e.target.value)}
        className="rounded-lg border border-primary px-4 py-2 w-full text-sm"
      />

      <div className="flex flex-wrap items-center gap-3">
        <label className="text-sm text-gray-600" htmlFor="ttsVoice">
          Voice:
        </label>
        <input
          id="ttsVoice"
          type="text"
          value={voice}
          onChange={(e) => setVoice(e.target.value)}
          disabled={busy}
          className="rounded-lg border border-gray-300 px-3 py-1.5 text-sm disabled:opacity-50"
        />
        <label className="text-sm text-gray-600" htmlFor="ttsLanguage">
          Language:
        </label>
        <input
          id="ttsLanguage"
          type="text"
          value={language}
          onChange={(e) => setLanguage(e.target.value)}
          disabled={busy}
          placeholder="e.g. en, es, fr"
          className="w-28 rounded-lg border border-gray-300 px-3 py-1.5 text-sm disabled:opacity-50"
        />
        <span className="text-xs text-gray-500">
          Discover voices and languages via <code className="font-mono">client.tts.listModels()</code>
        </span>
      </div>

      <div className="flex items-center gap-3 text-sm">
        <span
          className={`rounded-full px-3 py-0.5 text-xs font-medium ${STATE_COLORS[state] ?? 'bg-gray-200 text-gray-600'}`}
        >
          {state}
        </span>
      </div>

      {error && <div className="text-red-500 text-sm">Error: {error.message}</div>}

      <div className="flex gap-2">
        <Button onClick={onSpeak} disabled={busy || !text.trim()}>
          {busy ? 'Generating…' : 'Speak'}
        </Button>
        {busy && <Button onClick={cancel}>Cancel</Button>}
      </div>

      {audioUrl && <audio ref={audioRef} src={audioUrl} controls className="w-full" />}
    </div>
  );
}
